#!/bin/bash

source global

read -p "Czy wejsc do kontenera ${TEMPLATE}? (t/n):" ANS
if [ ${ANS} != 't' ] && [ ${ANS} != 'T' ]; then
  exit
fi

# Jesli nie istnieje kontener
if ! docker ps -a|grep -q ${TEMPLATE}; then 
  docker run -it ${RUNOPT} ${TEMPLATE}:latest
else
  # Jesli istnieje i nie jest uruchomiony
  if docker ps -a|grep ${TEMPLATE}|grep -q "Exited"; then
    docker start -ai ${TEMPLATE}
  else
    docker attach ${TEMPLATE}
  fi
fi

docker stop ${TEMPLATE}
docker rm ${TEMPLATE}
