#!/bin/bash

source global

read -p "Czy budowac obraz ${TEMPLATE}? (t/n): " ANS
if [ ${ANS} != 't' ] && [ ${ANS} != 'T' ]; then
  exit
fi

docker build -t ${TEMPLATE}:latest ./ \
&& docker run -d ${RUNOPT} ${TEMPLATE}:latest /bin/sleep 1000 \
&& KERNEL=$(docker exec ${TEMPLATE} readlink -f /vmlinuz) \
&& INITRD=$(docker exec ${TEMPLATE} readlink -f /initrd.img) \
&& docker exec ${TEMPLATE} update-initramfs -c -k all \
&& docker cp ${TEMPLATE}:${KERNEL} ./vmlinuz \
&& chmod go+r ./vmlinuz \
&& docker cp ${TEMPLATE}:${INITRD} ./initrd.img \
&& docker stop ${TEMPLATE} \
&& docker export ${TEMPLATE}|gzip > ./${TEMPLATE}.tgz \
&& docker rm ${TEMPLATE}
