#!/bin/sh
set -x
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line


# from /usr/share/initramfs-tools/scripts/nfs
manual_add_modules nfs
# For DHCP
manual_add_modules af_packet
copy_exec /sbin/dhclient
copy_exec ${BOCMDIR}/dhclient-script /sbin

copy_exec /bin/ln 

copy_exec /bin/chown

copy_exec /sbin/sgdisk /sbin
copy_exec /bin/lsblk /bin

copy_exec /sbin/mkfs.xfs /sbin
copy_exec /sbin/fsck.xfs /sbin
copy_exec /sbin/xfs_repair /sbin
copy_exec /usr/sbin/xfs_db /sbin
copy_exec /sbin/mkfs.vfat /sbin
copy_exec /sbin/mkswap /sbin
copy_exec /usr/bin/rsync /bin

copy_exec /usr/bin/head	/bin
copy_exec /usr/bin/md5sum /bin

copy_exec /bin/dd /bin
copy_exec /usr/bin/find /usr/bin/find

# Dodane po to by dzialal dns
for _LIBRARY in /lib/x86_64-linux-gnu/libnss_dns*
do
        if [ -e "${_LIBRARY}" ]
        then
                copy_exec ${_LIBRARY} /lib
        fi
done

copy_exec /bin/tar /bin
copy_exec /usr/bin/wget /usr/bin
copy_exec /bin/bash /bin/bash

exit 0
