#!/bin/sh
set -x
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

copy_exec /usr/bin/mfsmount
copy_exec /sbin/vconfig
#copy_exec /bin/ping

exit 0
